/*
Oman Oil & Natural Gas Company - SQL Server Database Design
Generated by Microsoft 365 Copilot
Purpose: Manage upstream operations, refinery operations, inventory, logistics, HSE, procurement and commercial data.

Run order:
1. 00_CreateDatabaseAndSchema.sql
2. 01_Seed_MasterData.sql
3. 02_Seed_OperationsData.sql
4. 03_Seed_Refinery_Commercial_Data.sql
5. 04_Indexes_Views_Validation.sql

Note: Each table is populated with 5,000 dummy records by the seed scripts.
*/

IF DB_ID('OmanOilGasDB') IS NULL
BEGIN
    CREATE DATABASE OmanOilGasDB;
END
GO

USE OmanOilGasDB;
GO

-- Drop tables in dependency order for repeatable execution
IF OBJECT_ID('dbo.PurchaseOrderLines','U') IS NOT NULL DROP TABLE dbo.PurchaseOrderLines;
IF OBJECT_ID('dbo.PurchaseOrders','U') IS NOT NULL DROP TABLE dbo.PurchaseOrders;
IF OBJECT_ID('dbo.Shipments','U') IS NOT NULL DROP TABLE dbo.Shipments;
IF OBJECT_ID('dbo.InventoryTransactions','U') IS NOT NULL DROP TABLE dbo.InventoryTransactions;
IF OBJECT_ID('dbo.RefineryBatches','U') IS NOT NULL DROP TABLE dbo.RefineryBatches;
IF OBJECT_ID('dbo.LabQualityTests','U') IS NOT NULL DROP TABLE dbo.LabQualityTests;
IF OBJECT_ID('dbo.HSEIncidents','U') IS NOT NULL DROP TABLE dbo.HSEIncidents;
IF OBJECT_ID('dbo.WellMaintenance','U') IS NOT NULL DROP TABLE dbo.WellMaintenance;
IF OBJECT_ID('dbo.ProductionDaily','U') IS NOT NULL DROP TABLE dbo.ProductionDaily;
IF OBJECT_ID('dbo.Customers','U') IS NOT NULL DROP TABLE dbo.Customers;
IF OBJECT_ID('dbo.Suppliers','U') IS NOT NULL DROP TABLE dbo.Suppliers;
IF OBJECT_ID('dbo.Products','U') IS NOT NULL DROP TABLE dbo.Products;
IF OBJECT_ID('dbo.RefineryUnits','U') IS NOT NULL DROP TABLE dbo.RefineryUnits;
IF OBJECT_ID('dbo.Pipelines','U') IS NOT NULL DROP TABLE dbo.Pipelines;
IF OBJECT_ID('dbo.Wells','U') IS NOT NULL DROP TABLE dbo.Wells;
IF OBJECT_ID('dbo.Equipment','U') IS NOT NULL DROP TABLE dbo.Equipment;
IF OBJECT_ID('dbo.Employees','U') IS NOT NULL DROP TABLE dbo.Employees;
IF OBJECT_ID('dbo.Departments','U') IS NOT NULL DROP TABLE dbo.Departments;
IF OBJECT_ID('dbo.Sites','U') IS NOT NULL DROP TABLE dbo.Sites;
GO

CREATE TABLE dbo.Sites (
    SiteID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Sites PRIMARY KEY,
    SiteCode AS ('SITE-' + RIGHT('00000' + CAST(SiteID AS VARCHAR(5)),5)) PERSISTED,
    SiteName NVARCHAR(150) NOT NULL,
    SiteType NVARCHAR(40) NOT NULL CHECK (SiteType IN ('Field','Refinery','Terminal','Depot','Office','Port','Storage')),
    Wilayat NVARCHAR(80) NOT NULL,
    Governorate NVARCHAR(80) NOT NULL,
    Latitude DECIMAL(9,6) NULL,
    Longitude DECIMAL(9,6) NULL,
    CommissionedDate DATE NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.Departments (
    DepartmentID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Departments PRIMARY KEY,
    DepartmentCode AS ('DEPT-' + RIGHT('00000' + CAST(DepartmentID AS VARCHAR(5)),5)) PERSISTED,
    DepartmentName NVARCHAR(150) NOT NULL,
    FunctionArea NVARCHAR(60) NOT NULL CHECK (FunctionArea IN ('Operations','Refinery','Maintenance','HSE','Finance','Supply Chain','HR','IT','Commercial','Projects')),
    SiteID INT NOT NULL CONSTRAINT FK_Departments_Sites REFERENCES dbo.Sites(SiteID),
    AnnualBudgetOMR DECIMAL(18,3) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.Employees (
    EmployeeID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Employees PRIMARY KEY,
    EmployeeCode AS ('EMP-' + RIGHT('00000' + CAST(EmployeeID AS VARCHAR(5)),5)) PERSISTED,
    FullName NVARCHAR(150) NOT NULL,
    JobTitle NVARCHAR(100) NOT NULL,
    DepartmentID INT NOT NULL CONSTRAINT FK_Employees_Departments REFERENCES dbo.Departments(DepartmentID),
    SiteID INT NOT NULL CONSTRAINT FK_Employees_Sites REFERENCES dbo.Sites(SiteID),
    HireDate DATE NOT NULL,
    ShiftPattern NVARCHAR(30) NOT NULL CHECK (ShiftPattern IN ('Day','Night','Rotational','Office')),
    Email NVARCHAR(150) NOT NULL,
    Phone NVARCHAR(40) NULL,
    IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE dbo.Equipment (
    EquipmentID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Equipment PRIMARY KEY,
    EquipmentCode AS ('EQP-' + RIGHT('00000' + CAST(EquipmentID AS VARCHAR(5)),5)) PERSISTED,
    EquipmentName NVARCHAR(150) NOT NULL,
    EquipmentType NVARCHAR(50) NOT NULL CHECK (EquipmentType IN ('Pump','Compressor','Separator','Turbine','Heat Exchanger','Tank','Valve','Generator','Meter','Control System')),
    SiteID INT NOT NULL CONSTRAINT FK_Equipment_Sites REFERENCES dbo.Sites(SiteID),
    Manufacturer NVARCHAR(100) NOT NULL,
    InstalledDate DATE NOT NULL,
    Criticality NVARCHAR(20) NOT NULL CHECK (Criticality IN ('Low','Medium','High','Safety Critical')),
    Status NVARCHAR(30) NOT NULL CHECK (Status IN ('Running','Standby','Maintenance','Out of Service'))
);

CREATE TABLE dbo.Wells (
    WellID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Wells PRIMARY KEY,
    WellCode AS ('WELL-' + RIGHT('00000' + CAST(WellID AS VARCHAR(5)),5)) PERSISTED,
    WellName NVARCHAR(150) NOT NULL,
    FieldSiteID INT NOT NULL CONSTRAINT FK_Wells_Sites REFERENCES dbo.Sites(SiteID),
    WellType NVARCHAR(30) NOT NULL CHECK (WellType IN ('Oil Producer','Gas Producer','Water Injector','Gas Injector','Exploration')),
    SpudDate DATE NOT NULL,
    DepthMeters DECIMAL(10,2) NOT NULL,
    Status NVARCHAR(30) NOT NULL CHECK (Status IN ('Producing','Shut-in','Drilling','Suspended','Abandoned')),
    Reservoir NVARCHAR(80) NOT NULL
);

CREATE TABLE dbo.Pipelines (
    PipelineID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Pipelines PRIMARY KEY,
    PipelineCode AS ('PIPE-' + RIGHT('00000' + CAST(PipelineID AS VARCHAR(5)),5)) PERSISTED,
    PipelineName NVARCHAR(150) NOT NULL,
    FromSiteID INT NOT NULL CONSTRAINT FK_Pipelines_FromSite REFERENCES dbo.Sites(SiteID),
    ToSiteID INT NOT NULL CONSTRAINT FK_Pipelines_ToSite REFERENCES dbo.Sites(SiteID),
    ProductCategory NVARCHAR(40) NOT NULL CHECK (ProductCategory IN ('Crude Oil','Natural Gas','Condensate','Refined Product','Water')),
    LengthKM DECIMAL(10,2) NOT NULL,
    DiameterInches DECIMAL(10,2) NOT NULL,
    MaxPressureBar DECIMAL(10,2) NOT NULL,
    Status NVARCHAR(30) NOT NULL CHECK (Status IN ('Active','Maintenance','Idle','Decommissioned'))
);

CREATE TABLE dbo.RefineryUnits (
    UnitID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_RefineryUnits PRIMARY KEY,
    UnitCode AS ('UNIT-' + RIGHT('00000' + CAST(UnitID AS VARCHAR(5)),5)) PERSISTED,
    UnitName NVARCHAR(150) NOT NULL,
    RefinerySiteID INT NOT NULL CONSTRAINT FK_RefineryUnits_Sites REFERENCES dbo.Sites(SiteID),
    UnitType NVARCHAR(60) NOT NULL CHECK (UnitType IN ('Crude Distillation','Hydrocracker','Reformer','Desulphurisation','Blending','Utilities','Storage','Wastewater')),
    CapacityBarrelsPerDay DECIMAL(18,2) NOT NULL,
    CommissionedDate DATE NOT NULL,
    Status NVARCHAR(30) NOT NULL CHECK (Status IN ('Running','Planned Shutdown','Maintenance','Standby'))
);

CREATE TABLE dbo.Products (
    ProductID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Products PRIMARY KEY,
    ProductCode AS ('PROD-' + RIGHT('00000' + CAST(ProductID AS VARCHAR(5)),5)) PERSISTED,
    ProductName NVARCHAR(150) NOT NULL,
    ProductCategory NVARCHAR(40) NOT NULL CHECK (ProductCategory IN ('Crude Oil','Natural Gas','LPG','Naphtha','Diesel','Jet Fuel','Gasoline','Fuel Oil','Sulphur','Bitumen')),
    UnitOfMeasure NVARCHAR(20) NOT NULL CHECK (UnitOfMeasure IN ('BBL','MT','MMBTU','M3','Litre')),
    StandardDensityKgM3 DECIMAL(10,3) NULL,
    IsHazardous BIT NOT NULL DEFAULT 0
);

CREATE TABLE dbo.Suppliers (
    SupplierID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Suppliers PRIMARY KEY,
    SupplierCode AS ('SUP-' + RIGHT('00000' + CAST(SupplierID AS VARCHAR(5)),5)) PERSISTED,
    SupplierName NVARCHAR(150) NOT NULL,
    SupplierCategory NVARCHAR(60) NOT NULL CHECK (SupplierCategory IN ('Chemicals','Equipment','Maintenance Services','Logistics','IT Services','Safety Supplies','Engineering','Catering')),
    Country NVARCHAR(80) NOT NULL,
    ContactEmail NVARCHAR(150) NOT NULL,
    Phone NVARCHAR(40) NULL,
    ApprovedVendor BIT NOT NULL DEFAULT 1,
    RiskRating NVARCHAR(20) NOT NULL CHECK (RiskRating IN ('Low','Medium','High'))
);

CREATE TABLE dbo.Customers (
    CustomerID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Customers PRIMARY KEY,
    CustomerCode AS ('CUST-' + RIGHT('00000' + CAST(CustomerID AS VARCHAR(5)),5)) PERSISTED,
    CustomerName NVARCHAR(150) NOT NULL,
    CustomerType NVARCHAR(40) NOT NULL CHECK (CustomerType IN ('Domestic','Export','Government','Industrial','Retail Distributor')),
    Country NVARCHAR(80) NOT NULL,
    ContactEmail NVARCHAR(150) NOT NULL,
    CreditLimitOMR DECIMAL(18,3) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE dbo.ProductionDaily (
    ProductionID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ProductionDaily PRIMARY KEY,
    ProductionDate DATE NOT NULL,
    WellID INT NOT NULL CONSTRAINT FK_ProductionDaily_Wells REFERENCES dbo.Wells(WellID),
    SiteID INT NOT NULL CONSTRAINT FK_ProductionDaily_Sites REFERENCES dbo.Sites(SiteID),
    OilBarrels DECIMAL(18,2) NOT NULL,
    GasMMscf DECIMAL(18,3) NOT NULL,
    WaterBarrels DECIMAL(18,2) NOT NULL,
    DowntimeHours DECIMAL(6,2) NOT NULL,
    OperatorEmployeeID INT NOT NULL CONSTRAINT FK_ProductionDaily_Employees REFERENCES dbo.Employees(EmployeeID),
    Remarks NVARCHAR(250) NULL
);

CREATE TABLE dbo.WellMaintenance (
    MaintenanceID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_WellMaintenance PRIMARY KEY,
    WorkOrderNo AS ('WO-' + RIGHT('000000' + CAST(MaintenanceID AS VARCHAR(6)),6)) PERSISTED,
    WellID INT NOT NULL CONSTRAINT FK_WellMaintenance_Wells REFERENCES dbo.Wells(WellID),
    EquipmentID INT NOT NULL CONSTRAINT FK_WellMaintenance_Equipment REFERENCES dbo.Equipment(EquipmentID),
    MaintenanceType NVARCHAR(50) NOT NULL CHECK (MaintenanceType IN ('Preventive','Corrective','Inspection','Calibration','Workover')),
    PlannedStartDate DATE NOT NULL,
    ActualCompletionDate DATE NULL,
    CostOMR DECIMAL(18,3) NOT NULL,
    SupervisorEmployeeID INT NOT NULL CONSTRAINT FK_WellMaintenance_Employees REFERENCES dbo.Employees(EmployeeID),
    Status NVARCHAR(30) NOT NULL CHECK (Status IN ('Planned','In Progress','Completed','Deferred','Cancelled'))
);

CREATE TABLE dbo.HSEIncidents (
    IncidentID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_HSEIncidents PRIMARY KEY,
    IncidentNo AS ('HSE-' + RIGHT('000000' + CAST(IncidentID AS VARCHAR(6)),6)) PERSISTED,
    IncidentDate DATE NOT NULL,
    SiteID INT NOT NULL CONSTRAINT FK_HSEIncidents_Sites REFERENCES dbo.Sites(SiteID),
    DepartmentID INT NOT NULL CONSTRAINT FK_HSEIncidents_Departments REFERENCES dbo.Departments(DepartmentID),
    IncidentType NVARCHAR(60) NOT NULL CHECK (IncidentType IN ('Near Miss','First Aid','Medical Treatment','Lost Time Injury','Spill','Fire','Vehicle','Gas Release')),
    Severity NVARCHAR(20) NOT NULL CHECK (Severity IN ('Low','Medium','High','Critical')),
    ReportedByEmployeeID INT NOT NULL CONSTRAINT FK_HSEIncidents_Employees REFERENCES dbo.Employees(EmployeeID),
    Description NVARCHAR(500) NOT NULL,
    CorrectiveAction NVARCHAR(500) NULL,
    ClosureStatus NVARCHAR(30) NOT NULL CHECK (ClosureStatus IN ('Open','Under Investigation','Closed'))
);

CREATE TABLE dbo.LabQualityTests (
    TestID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_LabQualityTests PRIMARY KEY,
    SampleNo AS ('LAB-' + RIGHT('000000' + CAST(TestID AS VARCHAR(6)),6)) PERSISTED,
    SampleDate DATE NOT NULL,
    ProductID INT NOT NULL CONSTRAINT FK_LabQualityTests_Products REFERENCES dbo.Products(ProductID),
    SiteID INT NOT NULL CONSTRAINT FK_LabQualityTests_Sites REFERENCES dbo.Sites(SiteID),
    DensityKgM3 DECIMAL(10,3) NOT NULL,
    SulphurPercent DECIMAL(8,4) NOT NULL,
    WaterContentPercent DECIMAL(8,4) NOT NULL,
    FlashPointC DECIMAL(8,2) NOT NULL,
    TestedByEmployeeID INT NOT NULL CONSTRAINT FK_LabQualityTests_Employees REFERENCES dbo.Employees(EmployeeID),
    ResultStatus NVARCHAR(20) NOT NULL CHECK (ResultStatus IN ('Pass','Fail','Retest'))
);

CREATE TABLE dbo.RefineryBatches (
    BatchID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_RefineryBatches PRIMARY KEY,
    BatchNo AS ('BATCH-' + RIGHT('000000' + CAST(BatchID AS VARCHAR(6)),6)) PERSISTED,
    UnitID INT NOT NULL CONSTRAINT FK_RefineryBatches_Units REFERENCES dbo.RefineryUnits(UnitID),
    InputProductID INT NOT NULL CONSTRAINT FK_RefineryBatches_InputProduct REFERENCES dbo.Products(ProductID),
    OutputProductID INT NOT NULL CONSTRAINT FK_RefineryBatches_OutputProduct REFERENCES dbo.Products(ProductID),
    BatchStart DATETIME2 NOT NULL,
    BatchEnd DATETIME2 NULL,
    InputVolumeBBL DECIMAL(18,2) NOT NULL,
    OutputVolumeBBL DECIMAL(18,2) NOT NULL,
    EnergyConsumedMWh DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(30) NOT NULL CHECK (Status IN ('Running','Completed','Quality Hold','Cancelled'))
);

CREATE TABLE dbo.InventoryTransactions (
    InventoryTxnID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_InventoryTransactions PRIMARY KEY,
    TransactionDate DATETIME2 NOT NULL,
    SiteID INT NOT NULL CONSTRAINT FK_InventoryTransactions_Sites REFERENCES dbo.Sites(SiteID),
    ProductID INT NOT NULL CONSTRAINT FK_InventoryTransactions_Products REFERENCES dbo.Products(ProductID),
    TransactionType NVARCHAR(20) NOT NULL CHECK (TransactionType IN ('Receipt','Issue','Transfer In','Transfer Out','Adjustment')),
    Quantity DECIMAL(18,3) NOT NULL,
    UnitOfMeasure NVARCHAR(20) NOT NULL CHECK (UnitOfMeasure IN ('BBL','MT','MMBTU','M3','Litre')),
    ReferenceDocument NVARCHAR(80) NOT NULL,
    CreatedByEmployeeID INT NOT NULL CONSTRAINT FK_InventoryTransactions_Employees REFERENCES dbo.Employees(EmployeeID)
);

CREATE TABLE dbo.Shipments (
    ShipmentID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Shipments PRIMARY KEY,
    ShipmentNo AS ('SHIP-' + RIGHT('000000' + CAST(ShipmentID AS VARCHAR(6)),6)) PERSISTED,
    ShipmentDate DATE NOT NULL,
    CustomerID INT NOT NULL CONSTRAINT FK_Shipments_Customers REFERENCES dbo.Customers(CustomerID),
    ProductID INT NOT NULL CONSTRAINT FK_Shipments_Products REFERENCES dbo.Products(ProductID),
    FromSiteID INT NOT NULL CONSTRAINT FK_Shipments_Sites REFERENCES dbo.Sites(SiteID),
    TransportMode NVARCHAR(30) NOT NULL CHECK (TransportMode IN ('Pipeline','Road Tanker','Marine Vessel','Rail')),
    Quantity DECIMAL(18,3) NOT NULL,
    UnitPriceOMR DECIMAL(18,3) NOT NULL,
    CurrencyCode CHAR(3) NOT NULL DEFAULT 'OMR',
    DeliveryStatus NVARCHAR(30) NOT NULL CHECK (DeliveryStatus IN ('Planned','Dispatched','Delivered','Delayed','Cancelled'))
);

CREATE TABLE dbo.PurchaseOrders (
    PurchaseOrderID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PurchaseOrders PRIMARY KEY,
    PONumber AS ('PO-' + RIGHT('000000' + CAST(PurchaseOrderID AS VARCHAR(6)),6)) PERSISTED,
    PODate DATE NOT NULL,
    SupplierID INT NOT NULL CONSTRAINT FK_PurchaseOrders_Suppliers REFERENCES dbo.Suppliers(SupplierID),
    DepartmentID INT NOT NULL CONSTRAINT FK_PurchaseOrders_Departments REFERENCES dbo.Departments(DepartmentID),
    BuyerEmployeeID INT NOT NULL CONSTRAINT FK_PurchaseOrders_Employees REFERENCES dbo.Employees(EmployeeID),
    POStatus NVARCHAR(30) NOT NULL CHECK (POStatus IN ('Draft','Approved','Partially Received','Closed','Cancelled')),
    TotalAmountOMR DECIMAL(18,3) NOT NULL
);

CREATE TABLE dbo.PurchaseOrderLines (
    PurchaseOrderLineID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PurchaseOrderLines PRIMARY KEY,
    PurchaseOrderID BIGINT NOT NULL CONSTRAINT FK_PurchaseOrderLines_PO REFERENCES dbo.PurchaseOrders(PurchaseOrderID),
    LineNo INT NOT NULL,
    ItemDescription NVARCHAR(250) NOT NULL,
    Quantity DECIMAL(18,3) NOT NULL,
    UnitPriceOMR DECIMAL(18,3) NOT NULL,
    RequiredDate DATE NOT NULL,
    ReceivedQuantity DECIMAL(18,3) NOT NULL DEFAULT 0,
    CONSTRAINT UQ_PurchaseOrderLines_PO_Line UNIQUE (PurchaseOrderID, LineNo)
);
GO